# Generated by Django 3.2.6 on 2021-12-07 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_desc', models.CharField(max_length=191)),
                ('category_img', models.ImageField(blank=True, upload_to='category_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('desc', models.TextField(max_length=3000)),
                ('contact', models.CharField(max_length=150)),
                ('comp_file', models.FileField(blank=True, upload_to='idea_file/')),
                ('score', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('participant_place', models.CharField(default='', max_length=191)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.category', verbose_name='دسته بندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
