# Generated by Django 3.2.6 on 2021-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_auto_20211205_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
