# Generated by Django 3.2.6 on 2021-12-08 22:34

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_rename_idea_idea_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea_bank',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
