# Generated by Django 3.2.6 on 2021-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20211208_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea_bank',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
