# Generated by Django 3.2.6 on 2021-12-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20211205_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, upload_to='category_image/'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='file',
            field=models.FileField(blank=True, upload_to='idea_file/'),
        ),
    ]
