# Generated by Django 3.2.6 on 2021-12-11 20:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_idea_bank_can_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea_bank',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
