# Generated by Django 3.2.6 on 2021-12-11 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0006_alter_idea_bank_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'موضوع رویداد ها', 'verbose_name_plural': 'موضوع رویداد ها'},
        ),
        migrations.AlterModelOptions(
            name='idea_bank',
            options={'verbose_name': 'بانک ایده ها', 'verbose_name_plural': 'بانک ایده ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_desc',
            field=models.CharField(max_length=191, verbose_name='موضوع دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, upload_to='category_image/', verbose_name='عکس دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='امکان ویرایش'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='comp_file',
            field=models.FileField(blank=True, upload_to='idea_file/', verbose_name='فرم بارگزاری شده'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='contact',
            field=models.CharField(max_length=150, verbose_name='مخاطبان'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='desc',
            field=models.TextField(verbose_name='چکیده'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='تایید ضده'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='like',
            field=models.IntegerField(default=0, verbose_name='تعداد علاقه مندی'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='participant_place',
            field=models.CharField(default='', max_length=191, verbose_name='محل برگزاری'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='score',
            field=models.IntegerField(blank=True, default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='title',
            field=models.CharField(max_length=191, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='ویرایش شده'),
        ),
        migrations.AlterField(
            model_name='idea_bank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
