# Generated by Django 3.2.6 on 2021-12-11 20:32

import ckeditor.fields
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='event_image')),
                ('file', models.FileField(blank=True, upload_to='event_form')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
