# Generated by Django 3.2.6 on 2021-12-11 22:25

import ckeditor.fields
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'رویداد ها', 'verbose_name_plural': 'رویداد ها'},
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='متن خبر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='file',
            field=models.FileField(blank=True, upload_to='event_form', verbose_name='فرم ها'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_image', verbose_name='تصویر خبر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=191, verbose_name='تیتر خبر'),
        ),
    ]
