# Generated by Django 3.2.6 on 2021-12-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner', models.ImageField(blank=True, upload_to='banner')),
                ('title', models.CharField(choices=[('m', 'main'), ('i', 'idea'), ('f', 'festival')], max_length=150)),
            ],
        ),
    ]
